#-------------------------------------------------------------------------------
# Copyright (C) 2017 Create-Net / FBK.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Create-Net / FBK - initial API and implementation
#-------------------------------------------------------------------------------
language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-core
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      VERSIONIST=true
      BASEIMAGE=resin\\/intel-nuc-zulujdk:8-jdk

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)
  - docker_upgrade
  - cache_load
  - bootstrap
  - echo "Tagging the build with tag - $DOCKER_TAG"

script:
  - docker_build_if_needed
  - git checkout Dockerfile
  - cache_save

after_success:
  - docker_push_if_needed
  - versionist_if_needed
