language: java

sudo: required
services:
  - docker

env:
  - IMAGE=agileiot/agile-core-x86_64
  - IMAGE=agileiot/agile-ble-x86_64

cache:
  directories:
    - $HOME/docker-cache/

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libglib2.0-0
      - libglib2.0-dev
      - curl

before_install:
  - if [ -f /home/travis/docker-cache/cache.tar.gz ]; then
      gunzip -c /home/travis/docker-cache/cache.tar.gz | docker load || true;
    fi
  - curl -SL https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz | tar -xzC . && chmod +x rocker
  - ./rocker build -f Rockerfile.amd64 .
  - docker tag agile-core-x86_64 $IMAGE:$TRAVIS_BRANCH
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
      mkdir -p $(dirname /home/travis/docker-cache/cache.tar.gz);
      docker save $(docker history -q $IMAGE:$TRAVIS_BRANCH | grep -v '<missing>') $(docker history -q agile-core-x86_64-builder | grep -v '<missing>') | gzip > /home/travis/docker-cache/cache.tar.gz;
    fi
install:
      - CC=clang CXX=clang++ CMAKE_C_COMPILER=clang CMAKE_CXX_COMPILER=clang++ scripts/install-deps.sh
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE:$TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag $IMAGE:$TRAVIS_BRANCH $IMAGE;
      docker push $IMAGE;
    fi