language: generic

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-ble
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/nuc-openjdk:openjdk-8-jdk

before_install:
  - if [ -f $DOCKER_CACHE_FILE ]; then
      gunzip -c $DOCKER_CACHE_FILE | docker load || true;
    fi

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - docker build -t $IMAGE:$TRAVIS_BRANCH .
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
      mkdir -p $(dirname ${DOCKER_CACHE_FILE});
      docker save $(docker history -q $IMAGE:$TRAVIS_BRANCH | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};
    fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE:$TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag $IMAGE:$TRAVIS_BRANCH $IMAGE;
      docker push $IMAGE;
    fi
