language: generic

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-core
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/nuc-openjdk:openjdk-8-jdk

before_install:
  - wget https://download.docker.com/linux/ubuntu/dists/trusty/pool/edge/amd64/docker-ce_17.04.0~ce-0~ubuntu-trusty_amd64.deb
  - sudo dpkg -i docker-ce_17.04.0~ce-0~ubuntu-trusty_amd64.deb
  - if [ -f $DOCKER_CACHE_FILE ]; then
      gunzip -c $DOCKER_CACHE_FILE | docker load || true;
    fi

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      export DOCKER_TAG=$TRAVIS_BRANCH-pr-$TRAVIS_PULL_REQUEST;
    else
      export DOCKER_TAG=$TRAVIS_BRANCH;
    fi
  - docker build -t $IMAGE:$DOCKER_TAG .
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
      mkdir -p $(dirname ${DOCKER_CACHE_FILE});
      docker save $(docker history -q $IMAGE:$DOCKER_TAG | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};
    fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE:$DOCKER_TAG;
  - if [ "$DOCKER_TAG" == "master" ]; then
      docker tag $IMAGE:$DOCKER_TAG $IMAGE;
      docker push $IMAGE;
    fi